version: "3.8"

services:
  api01: &api    
    image: marcelospfcufc/rinha-backend-2024:v1
    hostname: api01
    environment:
      - DB_URI=postgres://postgres:qpalzm@db_postgres/rinha_db?sslmode=disable&timezone=UTC
    restart: always
    tty: true
    command: ["/api2/main"]        
    ports:
      - "8081:8080"
    depends_on:
      - db_postgres
    volumes:
      - ./main:/api2/main
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  api02:
  #  # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api 
    hostname: api02
    environment:
      - DB_HOSTNAME=api2
    ports:
      - "8082:8080"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./configurations/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
  #     # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  db_postgres:
    image: postgres:latest
    hostname: db_postgres    
    environment:
      - POSTGRES_DB=rinha_db            
      - POSTGRES_PASSWORD=qpalzm
    ports:
      - "55432:5432"
    volumes:
    - ./configurations/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
    - ./configurations/docker-entrypoint-initdb.d/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "340MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1